name = "TSM"
uuid = "8f0ec7b0-9d77-4f68-b25b-9ce8d5f4f7e8"
version = "0.3.4"
authors = ["tcae <tcae@posteo.nl>"]

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EnvConfig = "a6e3057b-1cf6-47d2-8344-4f4d121c3bc7"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Targets = "08eb77dc-7627-4dc2-8b9a-0a9a8d02f815"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources]
EnvConfig = {path = "/Users/torsten/github/CryptoTimeSeries/EnvConfig"}
Targets = {path = "/Users/torsten/github/CryptoTimeSeries/Targets"}

[compat]
CategoricalArrays = "0.10.9"
DataFrames = "1.8.2"
Dates = "1.11.0"
Logging = "1.11.0"
julia = "1.5.3"
